// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MitarbeiterVerwaltung1.Data;

#nullable disable

namespace MitarbeiterVerwaltung1.Migrations
{
    [DbContext(typeof(MitarbeiterVerwaltung1DbContext))]
    [Migration("20250523174038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MitarbeiterVerwaltung1.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Geburtsdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produkte");
                });
#pragma warning restore 612, 618
        }
    }
}
